export type GoofyRiddle = { prompt: string; answer: string };

/**
 * Kid-leaning meme / brainrot tone — DM-only answers in session UI.
 * Large pool so repeat maps feel fresh.
 */
export const GOOFY_RIDDLES: GoofyRiddle[] = [
  { prompt: "What do you call a wizard who skips leg day?", answer: "A staff user with no carrying capacity." },
  { prompt: "I speak without a mouth and hear without ears. I have no body, but I come alive with fear… of group projects.", answer: "An echo (and also your group chat at 2am)." },
  { prompt: "What has keys but can’t open a single door?", answer: "A kobold with a keyring — wrong keys, wrong dungeon." },
  { prompt: "Why did the mimic go to therapy?", answer: "It couldn’t chest its feelings." },
  { prompt: "What’s orange, round, and sounds like a parrot?", answer: "A carrot doing a bad impression." },
  { prompt: "Before Mount Everest was discovered, what was the tallest mountain in the world?", answer: "Still Everest — perception checks aren’t geology." },
  { prompt: "What runs but never walks, murmurs but never talks, has a bed but never sleeps, has a mouth but never eats?", answer: "A river (and also the party’s bard)." },
  { prompt: "What has a spine but no bones?", answer: "A book — and also your excuses." },
  { prompt: "I’m tall when I’m young, I’m short when I’m old. What am I?", answer: "A candle — or a player who rolled stats badly." },
  { prompt: "What can travel around the world while staying in a corner?", answer: "A stamp — or a familiar on standby." },
  { prompt: "What has hands but can’t clap?", answer: "A clock — unless it’s cursed, then maybe it can." },
  { prompt: "Why don’t secrets work in a tavern?", answer: "Because the bar is always raising questions." },
  { prompt: "What did the barbarian say to the salad?", answer: "Lettuce rage." },
  { prompt: "Why was the skeleton calm during the boss fight?", answer: "He had no nerves left." },
  { prompt: "What’s a rogue’s favorite type of music?", answer: "Sneak beats." },
  { prompt: "Why don’t bards ever get lost?", answer: "They always follow the note road." },
  { prompt: "What do you get if you cross a ranger with a clock?", answer: "Someone who tracks time and tracks time." },
  { prompt: "Why did the paladin bring a ladder to the dungeon?", answer: "Lawful good reach." },
  { prompt: "What’s a wizard’s least favorite school subject?", answer: "Gym — too many saving throws." },
  { prompt: "Why was the dragon bad at social media?", answer: "Every post was flame-bait." },
  { prompt: "What do you call a sleepy warlock?", answer: "Pact-tired." },
  { prompt: "Why did the cleric break up with the necromancer?", answer: "Too many skeletons in the closet." },
  { prompt: "What’s fast, loud, and never finishes homework?", answer: "A speedrunner and also your little brother." },
  { prompt: "Why did the chicken join the adventuring party?", answer: "To get to the other side quest." },
  { prompt: "What has four legs in the morning, two in the afternoon, and orders too much takeout?", answer: "A college student (also kinda a werewolf)." },
  { prompt: "What’s Ohio’s official D&D alignment?", answer: "Chaotic neutral — nobody explains it, everyone memes it." },
  { prompt: "What do you call a sigma grindset paladin?", answer: "Lawful hustle." },
  { prompt: "Why did the bard lose the rap battle?", answer: "No counterspell prepared." },
  { prompt: "What’s the bard’s favorite snack?", answer: "Doritos — because they’re loud in initiative." },
  { prompt: "Why don’t mimics use TikTok?", answer: "They’d chest every trend." },
  { prompt: "What’s a goblin’s favorite subject?", answer: "Loot-erature." },
  { prompt: "Why was the troll banned from the forum?", answer: "Couldn’t stop feeding." },
  { prompt: "What do you call a cat in plate armor?", answer: "Heavy meow-tal." },
  { prompt: "Why did the party bring bread to the lich fight?", answer: "For counter-spells and sandwiches." },
  { prompt: "What’s a beholder’s worst fear?", answer: "Contact lenses." },
  { prompt: "Why did the gelatinous cube get promoted?", answer: "It absorbed the competition." },
  { prompt: "What’s a kobold’s favorite game?", answer: "Trap Royale." },
  { prompt: "Why was the ghost invited to karaoke?", answer: "He could hit the high wail." },
  { prompt: "What do you call a bard who only knows one song?", answer: "A one-hit wonder — literally." },
  { prompt: "Why don’t rust monsters use phones?", answer: "They hate iOS and oxidize Android." },
  { prompt: "What’s a dwarf’s favorite social network?", answer: "Mine-craft." },
  { prompt: "Why did the druid bring Wi‑Fi to the forest?", answer: "To log in." },
  { prompt: "What’s the scariest thing in the Underdark?", answer: "Group project with no healer." },
  { prompt: "Why did the fighter study art?", answer: "To master the slash technique." },
  { prompt: "What do you call a monk who meditates in traffic?", answer: "Zen and the art of honking." },
  { prompt: "Why was the vampire bad at streaming?", answer: "Buffering during daylight." },
  { prompt: "What’s a pirate wizard’s favorite spell?", answer: "Arrr-mor of Agathys." },
  { prompt: "Why don’t oozes play chess?", answer: "They always slime the king." },
  { prompt: "What’s a ranger’s favorite pizza?", answer: "Thin crust — they track everything." },
  { prompt: "Why did the sorcerer wear sunglasses?", answer: "Too many radiant soul moments." },
  { prompt: "What do you call a bard who only rolls natural 1s?", answer: "The blues." },
  { prompt: "Why did the party bard get a standing ovation?", answer: "They finally stopped talking." },
  { prompt: "What’s a mimic’s favorite holiday?", answer: "Boxing Day." },
  { prompt: "Why did the wizard install antivirus?", answer: "Scared of hex files." },
  { prompt: "What’s a zombie’s favorite app?", answer: "Brain-stagram." },
  { prompt: "Why don’t dragons use umbrellas?", answer: "Their breath already makes it rain." },
  { prompt: "What do you call a polite owlbear?", answer: "A ‘hoot-hoot’ bear." },
  { prompt: "Why was the dungeon cold?", answer: "Too many chill touch cantrips." },
  { prompt: "What’s a warlock’s favorite exercise?", answer: "Eldritch curls." },
  { prompt: "Why did the rogue wear bells?", answer: "They misunderstood ‘stealth rock’." },
  { prompt: "What do you call a bard’s backup plan?", answer: "Chord progression." },
  { prompt: "Why don’t mind flayers use emojis?", answer: "They only speak in brain-text." },
  { prompt: "What’s a goblin’s favorite cereal?", answer: "Lucky Charisma." },
  { prompt: "Why did the paladin refuse the haunted house?", answer: "Smite first, questions later." },
  { prompt: "What do you call a skeleton DJ?", answer: "Bone-thugs-n-harmony." },
  { prompt: "Why was the druid banned from the salad bar?", answer: "Speak with plants got too real." },
  { prompt: "What’s a tiefling’s favorite dessert?", answer: "Infernal chocolate lava cake." },
  { prompt: "Why did the barbarian fail stealth?", answer: "Rage quit quiet mode." },
  { prompt: "What do you call a wizard who only knows Minor Illusion?", answer: "A JPEG caster." },
  { prompt: "Why don’t liches play basketball?", answer: "They always travel — centuries." },
  { prompt: "What’s a fish’s favorite D&D class?", answer: "School of Evocation." },
  { prompt: "Why did the party bring a rubber duck to the puzzle room?", answer: "For debug mode." },
  { prompt: "What do you call a bard who only speaks in puns?", answer: "Pun-ishment." },
  { prompt: "Why was the ghost bad at hide-and-seek?", answer: "Always peeking." },
  { prompt: "What’s a kobold’s Wi‑Fi password?", answer: "TRAP1234." },
  { prompt: "Why did the cleric bless the router?", answer: "For divine connection." },
  { prompt: "What do you call a sleepy dragon?", answer: "A napalm." },
  { prompt: "Why don’t rust monsters order soda?", answer: "They prefer metal thirst." },
  { prompt: "What’s a rogue’s favorite fruit?", answer: "Sneak-ers (sneakers)." },
  { prompt: "Why did the wizard fail driving school?", answer: "Kept misty stepping the clutch." },
  { prompt: "What do you call a party with no healer?", answer: "A speedrun to a TPK." },
  { prompt: "Why was the mimic invited to the potluck?", answer: "It brought the best dishes — literally." },
  { prompt: "What’s a bard’s favorite fish?", answer: "Tuna — for the scales." },
  { prompt: "Why don’t elementals use elevators?", answer: "They prefer plane travel." },
  { prompt: "What do you call a paladin who loves brunch?", answer: "Lawful good avocado toast." },
  { prompt: "Why did the skeleton go to the party alone?", answer: "He had nobody to go with." },
  { prompt: "What’s a wizard’s favorite browser?", answer: "Chrome — for the shiny." },
  { prompt: "Why was the gelatinous cube a good roommate?", answer: "Always cleaned the floor." },
  { prompt: "What do you call a bard who only rolls 20s?", answer: "Suspicious." },
  { prompt: "Why don’t beholders play fair?", answer: "Too many eyes on the prize." },
  { prompt: "What’s a dwarf’s least favorite song?", answer: "Highway to the danger zone — too much sky." },
  { prompt: "Why did the rogue multiclass into chef?", answer: "Sneak attack with flavor." },
  { prompt: "What do you call a tired warlock patron?", answer: "A nap-pact." },
  { prompt: "Why was the dungeon boss late?", answer: "Spawn timer." },
  { prompt: "What’s a zombie’s favorite dance?", answer: "The sham-ble." },
  { prompt: "Why don’t dragons share treasure?", answer: "Hoard feelings." },
  { prompt: "What do you call a cleric who only heals themselves?", answer: "Self-care paladin." },
  { prompt: "Why did the mimic fail art class?", answer: "Could only draw chests." },
  { prompt: "What’s a kobold’s life motto?", answer: "Work smarter, trap harder." },
  { prompt: "Why was the lich invited to trivia night?", answer: "He knew all the dead answers." },
  { prompt: "What do you call a bard’s worst enemy?", answer: "Silence — it’s overpowered." },
  { prompt: "Why don’t oozes use calendars?", answer: "Every day is a blur." },
  { prompt: "What’s a ranger’s favorite weather?", answer: "Fog — advantage on dramatic entrances." },
  { prompt: "Why did the barbarian bring glue to combat?", answer: "To stick to the plan." },
  { prompt: "What do you call a wizard’s shopping list?", answer: "Spell components and impulse buys." },
  { prompt: "Why was the ghost a bad cashier?", answer: "Couldn’t handle change." },
  { prompt: "What’s a fish’s least favorite spell?", answer: "Lightning bolt — too shocking." },
  { prompt: "Why did the party bard get muted on Discord?", answer: "Vicious mockery IRL." },
  { prompt: "What do you call a paladin who loves puns?", answer: "Lawful pun-ishment." },
  { prompt: "Why don’t mind flayers eat fast food?", answer: "They prefer fresh thoughts." },
  { prompt: "What’s a goblin’s dream job?", answer: "Middle management — already evil." },
  { prompt: "Why was the druid kicked out of the mall?", answer: "Entangle on the escalator." },
  { prompt: "What do you call a rogue who tells the truth?", answer: "A bard in disguise." },
  { prompt: "Why don’t vampires play Among Us?", answer: "Too sus in mirrors." },
  { prompt: "What’s a skeleton’s favorite instrument?", answer: "The trom-bone." },
  { prompt: "Why did the sorcerer wear a cape indoors?", answer: "Charisma modifier." },
  { prompt: "What do you call a dungeon with no loot?", answer: "A disappointment — also called ‘Tuesday’." },
  { prompt: "Why was the mimic a bad therapist?", answer: "Always projecting chest issues." },
  { prompt: "What’s a bard’s favorite planet?", answer: "Saturn — it has rings (of power)." },
  { prompt: "Why don’t rust monsters use laptops?", answer: "They’re not compatible with Macs." },
  { prompt: "What do you call a tired barbarian?", answer: "A nap-barian." },
  { prompt: "Why did the wizard fail gym class?", answer: "Mage Armor doesn’t count as participation." },
  { prompt: "What’s a dragon’s favorite social media?", answer: "Burn-terest." },
  { prompt: "Why was the ghost good at math?", answer: "Knows all the dead-imals." },
  { prompt: "What do you call a party that splits the party?", answer: "A horror movie." },
  { prompt: "Why don’t liches use sunscreen?", answer: "They’re already bone-dry." },
  { prompt: "What’s a kobold’s favorite movie?", answer: "Home Alone — trap respect." },
  { prompt: "Why did the cleric bless the dice?", answer: "For holy rollers." },
  { prompt: "What do you call a bard who only knows limericks?", answer: "A poet with commitment issues." },
  { prompt: "Why was the gelatinous cube invited to the pool party?", answer: "It brought the acid vibes." },
  { prompt: "What’s a rogue’s favorite letter?", answer: "S — for sneak and also for sigh." },
  { prompt: "Why don’t beholders wear hats?", answer: "No good angle." },
  { prompt: "What do you call a wizard who runs out of spell slots?", answer: "A tourist." },
  { prompt: "Why did the barbarian study geography?", answer: "To rage across the map." },
  { prompt: "What’s a mimic’s favorite board game?", answer: "Sorry! — it’s always in the box." },
  { prompt: "Why was the skeleton fired from the orchestra?", answer: "No guts, no glory notes." },
  { prompt: "What do you call a paladin who oversleeps?", answer: "Lawful neutral snooze." },
  { prompt: "Why don’t oozes play soccer?", answer: "They slide tackle everything." },
  { prompt: "What’s a fish’s favorite class feature?", answer: "Evasion — splash damage." },
  { prompt: "Why did the party bring a lawyer to the dragon?", answer: "For breach of contract (the castle wall)." },
  { prompt: "What do you call a bard who only whispers?", answer: "ASMR attack." },
  { prompt: "Why was the ghost bad at poker?", answer: "Always showing dead tells." },
  { prompt: "What’s a dwarf’s favorite keyboard?", answer: "Mechanical — clack is life." },
  { prompt: "Why don’t rust monsters order dessert?", answer: "Sweet tooth oxidizes." },
  { prompt: "What do you call a warlock’s diary?", answer: "The pact journal." },
  { prompt: "Why did the druid refuse plastic straws?", answer: "Wild shape, not waste shape." },
  { prompt: "What’s a zombie’s favorite subject?", answer: "History — it’s all past tense." },
  { prompt: "Why was the mimic voted ‘most likely to succeed’?", answer: "It always fits in." },
  { prompt: "What do you call a rogue who trips every trap?", answer: "A learning opportunity." },
  { prompt: "Why don’t dragons use GPS?", answer: "They wing it." },
  { prompt: "What’s a kobold’s favorite number?", answer: "3 — it’s a trap pyramid." },
  { prompt: "Why did the cleric bring snacks to the séance?", answer: "For spirit fingers and chips." },
  { prompt: "What do you call a bard at a library?", answer: "Banned — too loud." },
  { prompt: "Why was the gelatinous cube a good listener?", answer: "It absorbed everything you said." },
  { prompt: "What’s a paladin’s favorite mode of transport?", answer: "Find Steed Uber." },
  { prompt: "Why don’t mind flayers use voice chat?", answer: "Telepathy only — no mic checks." },
  { prompt: "What do you call a tired dungeon master?", answer: "Still rolling — clinically." },
];

export function pickGoofyRiddle(rng: () => number): GoofyRiddle {
  return GOOFY_RIDDLES[Math.floor(rng() * GOOFY_RIDDLES.length)]!;
}
